### ISSUE TITLE
Feature request: describe rpm/deb creation

### ISSUE THREAD

**Issue by neurolabusc** [davidbannon/libqt5pas#1]
The /cbindings/README.TXTdescribes how to compile and install the library locally. Can you extend the README.md to describe the process of creating .rpm and .deb files?

**Comment by davidbannon** [comment]
Hi Chris, see package.readme, its my own notes.  Whats not covered there os the setup of the system, must have gcc installed which brings along all the usual build tools.

package.readme is pretty terse, more intended for my use than anyone else but it does have all you need.

Davo

**Comment by neurolabusc** [comment]
Missed that. Thanks again!
