### ISSUE TITLE
*dev files in Release

### ISSUE THREAD

**Issue by Alexey-T** [davidbannon/libqt5pas#10]
```
libqt5pas-dev-2.10-2.armhf.rpm 174 KB 2022-11-07T08:25:33Z
libqt5pas-dev-2.10-2.x86_64.rpm 174 KB 2022-03-01T11:00:27Z
libqt5pas-dev_2.10-0_arm64.deb 137 KB 2022-11-07T09:43:43Z
libqt5pas-dev_2.10-0_armhf.deb 137 KB 2022-11-07T08:25:39Z
```
these 'dev' files. they are MUCH smaller and it seems files have only some broken symlink (not pointing to real file). I did not use them and only used 
libqt5pas1_2.10-0_arm64.deb  .

**Comment by davidbannon** [comment]
The dev files appear to have a broken symlink but when installed, it points to the real library, so, not broken.

Yep, dev files have heaps of documentation, license data, permissions to use and so on. In actual fact, on most cases (all in my experience) all a dev package does is make a symlink to an existing library but with the base name. So this is typical -
```
lrwxrwxrwx 1 root root       19 Mar  1  2022 /usr/lib/x86_64-linux-gnu/libQt5Pas.so -> libQt5Pas.so.1.2.10
lrwxrwxrwx 1 root root       19 Mar  1  2022 /usr/lib/x86_64-linux-gnu/libQt5Pas.so.1 -> libQt5Pas.so.1.2.10
-rw-r--r-- 1 root root  2669288 Mar  1  2022 /usr/lib/x86_64-linux-gnu/libQt5Pas.so.1.2.10
```
libQt5Pas.so.1.2.10 is the library, libQt5Pas.so.1 is a symlink that eg Lazarus looks for and libQt5Pas.so is the symlink made by the dev package. I often don't bother to install to install dev packages, just make a symlink to the actual library with its base name.

For example, I just rebuilt my release build VM (make RasPi Qt5), I forgot to install all the dev libraries on the machine I was copying the libraries from, so, in the build machine just made the appropriate symlink, some Qt5 files, libqt5pas, libgmodule, libgdk_pixel etc. It all built fine with no dev packages installed.


Davo
