### ISSUE TITLE
Add cmake based build script

### ISSUE THREAD

**Issue by iahung** [davidbannon/libqt5pas#13]
qmake generated makefile based project that building very slow on my system even if I specified make jobs equals to the cores of my cpu so I managed to write a cmake based buid script to use with the ninja generator and it's really much faster.

[CMakeLists.txt](https://github.com/davidbannon/libqt5pas/files/10076755/CMakeLists.txt)

**Comment by davidbannon** [comment]
Thanks iahung, however, I must maintain here the 'official' build system for the cbindings. The developer of this code might be interested (See the Lazarus Repo) but I expect any build system needs to be able to be auto generated. The list is quite long and if the maintainer of the code adopted your cmake list, every time a change was made, he would need to edit the very long cmakelists.txt file, well, that how mistakes are made. 

Use it yourself by all means, if you are rebuilding a lot it might be a good thing but I have not rebuilt for over six months so an extra 15 minutes of build time makes no difference to me. Much more important that I produce exactly the same result as the developer.

Thanks

Davo
