### ISSUE TITLE
Seems an update is needed after 2021.04

### ISSUE THREAD

**Issue by Alexey-T** [davidbannon/libqt5pas#3]
https://bugs.freepascal.org/view.php?id=38604
comments in that issue tell that qt5pas is changed.
@pascaldragon FYI

**Comment by pascaldragon** [comment]
Why are you referencing me? I'm not at all involved with the Qt interface or the library 🤔

**Comment by Alexey-T** [comment]
sorry to bother you.

**Comment by davidbannon** [comment]
yep, I will see if I can find some time this evening.
Thanks for the heads up.
Davo

**Comment by davidbannon** [comment]
OK Alexey, I have pushed out version 1.2.9 - if you are using these new features, I would appreciate it if you could do some testing.

Davo

**Comment by neurolabusc** [comment]
@davidbannon Thanks. you may want to announce this [this new version](https://forum.lazarus.freepascal.org/index.php/topic,54010.0.html).

**Comment by Alexey-T** [comment]
Installed the release, CudaText is working! good
