### ISSUE TITLE
Update README.md for 1.2.9

### ISSUE THREAD

**Issue by neurolabusc** [davidbannon/libqt5pas#4]
The recent new release is [1.2.9](https://github.com/davidbannon/libqt5pas/releases/tag/v1.2.9), consistent with the [Lazarus forums](https://forum.lazarus.freepascal.org/index.php/topic,54010.15.html). However, the README.md for this repository still refers to 1.2.8, and should be updated.

**Comment by davidbannon** [comment]
Yeah, good catch Chris, thats.  Updated it generally, including dropping my proposed versioning model, Z does not seem interested in that. But as long as he increments the number I will be happy.
Davo

**Comment by davidbannon** [comment]
way past time I closed this.
Davo

**Comment by davidbannon** [comment]
way, way past time I closed this.
Davo
