### ISSUE TITLE
Webkit & Webengine text fields

### ISSUE THREAD

**Issue by snoozamoorooed** [davidbannon/libqt5pas#7]
Hi David.
I'm interesting of using qt5 webkit or webengine with lazarus.
At the moment the only way to use these widgets is to create them from a wrapper library and then attach to a running form.
So i recompiled this libqt5pas library and re-added webkit and webengine wrapper functions back because they were excluded for a while.
Both widgets are loaded and displayed but ... if i load https://google.com keyboard input doesn't seem to work.
Hardware keyboard doesn't work in both cases while virtual keyboard (from a webpage) works only with webengine.
Also when i click inside a text field in a page loaded in webengine i see cursor for a moment and then it disappears.
Webkit text fields do not show cursor at all.
I also recompiled lazarus with qt4 to check webkit behavior with bundled libqtpas library and it was all the same: no cursor and no keyboard input.
Have you seen such behavior before ? May be there is something else to do to make it work.
Here is what i did inside lazarus code.

  Widget := TQtMainWindow(Self.Handle);
  w:=widget.GetContainerWidget;
  v := QWebView_create(w);
  QWidget_setGeometry(v,0,0,Width,Height);
  QWidget_show(v);
  url := 'https://google.com';
  qurl :=  QURL_create(@url);
  QWebView_load(v, qurl);

Operating system is Ubuntu 22.
Same code compiled with c++ / qt works fine.
Both webkit and webengine widgets work as expected.
Thanks.
Ivan

**Comment by davidbannon** [comment]
Ivan, I don't use or know anything about webkit I am afraid. But there seem to be a number of mentions about it on the Lazarus forum, i suggest you search through there for it, maybe join and ask your question there.

https://forum.lazarus.freepascal.org

More mention of GTK than Qt but that probably reflects actual usage too.

Davo

**Comment by davidbannon** [comment]
nothing to see here folks, move along ...
